version: "3.3"
services:
    project-manager-api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: project-manager-api
        depends_on:
            - project-manager-db
        ports:
            - 8081:80
        volumes:
            - ./api:/usr/src/app/api
    project-manager-frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: project-manager-frontend
        depends_on:
            - project-manager-api
        ports:
            - 80:8080
        volumes:
            - ./frontend:/usr/src/app/frontend
            - /usr/src/app/frontend/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
    # project-manager-frontend:
    #     build:
    #         context: ./frontend
    #         dockerfile: Dockerfile
    #     container_name: project-manager-frontend
    #     restart: always
    #     depends_on:
    #         - project-manager-api
    #     ports:
    #         - 80:5000
    #     volumes:
    #         - ./frontend:/usr/src/app/frontend
    #         - /usr/src/app/frontend/node_modules
    #     environment:
    #         - CHOKIDAR_USEPOLLING=true
    #         - HOST=0.0.0.0
    project-manager-db:
        image: postgres
        container_name: project-manager-db
        environment:
            POSTGRES_PASSWORD: rootpassword
            POSTGRES_DB: projects
        ports:
            - 5432:5432
        volumes:
            - project_manager_db_data_container:/data/db
    project-manager-admin:
        image: adminer
        container_name: project-manager-admin
        ports:
            - 8082:8080
        depends_on:
            - project-manager-db
volumes:
  project_manager_db_data_container:
